"""Arkansas place names, from the 2023 Census Gazetteer (state FIPS 05).

Used to split the ADH's run-together address blob into street and city:
the site renders '{street} {city}, AR {zip}' with no reliable delimiter, so we
match the longest known place name at the end of the string. Ordered
longest-first so "North Little Rock" wins over "Little Rock".
"""

AR_PLACES = [
    "Hot Springs Village",
    "Lost Bridge Village",
    "North Little Rock",
    "Oak Grove Heights",
    "South Lead Hill",
    "De Valls Bluff",
    "Helena-West Helena",
    "Wiederkehr Village",
    "Yarborough Landing",
    "Fredonia (Biscoe)",
    "Campbell Station",
    "Cherokee Village",
    "Ravenden Springs",
    "Cammack Village",
    "College Station",
    "Crystal Springs",
    "Mineral Springs",
    "Pleasant Plains",
    "Sulphur Springs",
    "Tumbling Shoals",
    "Eureka Springs",
    "Holiday Island",
    "Horseshoe Bend",
    "Horseshoe Lake",
    "Mammoth Spring",
    "Morrison Bluff",
    "Mount Pleasant",
    "North Crossett",
    "Pleasant Grove",
    "Siloam Springs",
    "Valley Springs",
    "Whelen Springs",
    "Arkansas City",
    "Black Springs",
    "Blue Mountain",
    "Cherokee City",
    "Cherry Valley",
    "Evening Shade",
    "Fairfield Bay",
    "Fountain Hill",
    "Fountain Lake",
    "Heber Springs",
    "Hickory Ridge",
    "Junction City",
    "Lake Hamilton",
    "Mountain Home",
    "Mountain Pine",
    "Mountain View",
    "Natural Steps",
    "Peach Orchard",
    "Prairie Creek",
    "Prairie Grove",
    "Shannon Hills",
    "West Crossett",
    "Western Grove",
    "Witts Springs",
    "Buffalo City",
    "Caddo Valley",
    "Cave Springs",
    "Center Point",
    "Center Ridge",
    "Central City",
    "Cotton Plant",
    "Diamond City",
    "Forrest City",
    "Green Forest",
    "Greers Ferry",
    "Lake Village",
    "Little Flock",
    "Mount Vernon",
    "New Edinburg",
    "Pencil Bluff",
    "Poplar Grove",
    "Sulphur Rock",
    "Walnut Ridge",
    "Warm Springs",
    "West Memphis",
    "Bella Vista",
    "Bull Shoals",
    "Calico Rock",
    "East Camden",
    "Elm Springs",
    "Gum Springs",
    "Holly Grove",
    "Hot Springs",
    "Jones Mills",
    "Little Rock",
    "Magnet Cove",
    "Marked Tree",
    "Mount Holly",
    "Mount Judea",
    "Mount Olive",
    "Ozark Acres",
    "St. Charles",
    "St. Francis",
    "Twin Groves",
    "Violet Hill",
    "Bee Branch",
    "Ben Lomond",
    "Black Rock",
    "Bluff City",
    "Board Camp",
    "Fort Smith",
    "Indian Bay",
    "New Blaine",
    "Oil Trough",
    "Pine Bluff",
    "Sweet Home",
    "West Point",
    "White Hall",
    "Bald Knob",
    "Black Oak",
    "Caddo Gap",
    "Cave City",
    "Coal Hill",
    "El Dorado",
    "Fair Oaks",
    "Lake City",
    "Lake View",
    "Lead Hill",
    "Mount Ida",
    "Oak Grove",
    "Pea Ridge",
    "Star City",
    "Van Buren",
    "West Fork",
    "Ash Flat",
    "Big Flat",
    "Blue Eye",
    "De Queen",
    "East End",
    "Rose Bud",
    "St. Paul",
    "Des Arc",
    "El Paso",
    "St. Joe",
    "Crawfordsville",
    "Griffithville",
    "Mitchellville",
    "Anthonyville",
    "Fayetteville",
    "Jacksonville",
    "Mountainburg",
    "Murfreesboro",
    "Russellville",
    "Wrightsville",
    "Arkadelphia",
    "Bentonville",
    "Blytheville",
    "Caulksville",
    "Centerville",
    "Clarksville",
    "Hattieville",
    "Jacksonport",
    "Plumerville",
    "Prattsville",
    "Springfield",
    "Vandervoort",
    "Willisville",
    "Batesville",
    "Beedeville",
    "Bellefonte",
    "Belleville",
    "Berryville",
    "Booneville",
    "Briarcliff",
    "Cedarville",
    "Charleston",
    "Cincinnati",
    "Clarkedale",
    "Dardanelle",
    "Delaplaine",
    "Evansville",
    "Farmington",
    "Felsenthal",
    "Friendship",
    "Georgetown",
    "Greenbrier",
    "Hagarville",
    "Harrisburg",
    "Hindsville",
    "Huntington",
    "Huntsville",
    "Leachville",
    "Lewisville",
    "Lockesburg",
    "Monticello",
    "Moorefield",
    "Perryville",
    "Pocahontas",
    "Pottsville",
    "Salesville",
    "Smithville",
    "Springdale",
    "Springtown",
    "Strawberry",
    "Waldenburg",
    "Washington",
    "Winchester",
    "Alexander",
    "Altheimer",
    "Brookland",
    "Centerton",
    "Chidester",
    "Clarendon",
    "Donaldson",
    "Edmondson",
    "Fifty-Six",
    "Gassville",
    "Greenland",
    "Greenwood",
    "Henderson",
    "Hermitage",
    "Higginson",
    "Jerusalem",
    "Jonesboro",
    "Kingsland",
    "Knoxville",
    "Mansfield",
    "Marmaduke",
    "Mayflower",
    "Maysville",
    "McCaskill",
    "Melbourne",
    "Morrilton",
    "Nashville",
    "Palestine",
    "Paragould",
    "Patterson",
    "Perrytown",
    "Pineville",
    "Plainview",
    "Princeton",
    "Rivervale",
    "Smackover",
    "Southside",
    "Stuttgart",
    "Texarkana",
    "Tontitown",
    "Traskwood",
    "Tuckerman",
    "Uniontown",
    "Wabbaseka",
    "Williford",
    "Yellville",
    "Appleton",
    "Bethesda",
    "Birdsong",
    "Bismarck",
    "Bradford",
    "Brinkley",
    "Burdette",
    "Caldwell",
    "Canehill",
    "Carlisle",
    "Carthage",
    "Crossett",
    "Damascus",
    "Danville",
    "Edgemont",
    "Franklin",
    "Gamaliel",
    "Garfield",
    "Glenwood",
    "Gravette",
    "Greenway",
    "Harrison",
    "Hartford",
    "Hatfield",
    "Highfill",
    "Highland",
    "Humphrey",
    "Jennette",
    "Judsonia",
    "Kingston",
    "LaGrange",
    "Lakeview",
    "Landmark",
    "Lonsdale",
    "Magazine",
    "Magnolia",
    "Marianna",
    "Marshall",
    "Maumelle",
    "McAlmont",
    "McDougal",
    "Mellwood",
    "Montrose",
    "Mulberry",
    "Norphlet",
    "Oakhaven",
    "Pangburn",
    "Parkdale",
    "Payneway",
    "Portland",
    "Powhatan",
    "Prescott",
    "Ratcliff",
    "Ravenden",
    "Redfield",
    "Rockport",
    "Rockwell",
    "Saratoga",
    "Scranton",
    "Sedgwick",
    "Sheridan",
    "Sherrill",
    "Sherwood",
    "Sparkman",
    "Stephens",
    "Thornton",
    "Tollette",
    "Vanndale",
    "Victoria",
    "Wheatley",
    "Winthrop",
    "Woodlawn",
    "Alleene",
    "Allport",
    "Antoine",
    "Armorel",
    "Ashdown",
    "Augusta",
    "Barling",
    "Bassett",
    "Batavia",
    "Bauxite",
    "Bearden",
    "Bergman",
    "Bigelow",
    "Biggers",
    "Blevins",
    "Bonanza",
    "Bradley",
    "Buckner",
    "Caraway",
    "Chester",
    "Clinton",
    "Collins",
    "Concord",
    "Corinth",
    "Corning",
    "Cushman",
    "Decatur",
    "Delight",
    "Dennard",
    "Denning",
    "Dermott",
    "Emerson",
    "England",
    "Everton",
    "Flippin",
    "Fordyce",
    "Foreman",
    "Fourche",
    "Garland",
    "Gateway",
    "Gilbert",
    "Gillett",
    "Gillham",
    "Gilmore",
    "Goodwin",
    "Gosnell",
    "Grannis",
    "Gregory",
    "Hackett",
    "Hamburg",
    "Hampton",
    "Harrell",
    "Hartman",
    "Haskell",
    "Hensley",
    "Holland",
    "Horatio",
    "Houston",
    "Humnoke",
    "Imboden",
    "Jericho",
    "Johnson",
    "Kensett",
    "Lepanto",
    "Lincoln",
    "Madison",
    "Magness",
    "Malvern",
    "Marvell",
    "Maynard",
    "McCrory",
    "McGehee",
    "Menifee",
    "Midland",
    "Minturn",
    "Monette",
    "Newhope",
    "Newport",
    "Nimmons",
    "Norfork",
    "Oakland",
    "Okolona",
    "Osceola",
    "Piggott",
    "Pindall",
    "Pollard",
    "Quitman",
    "Rosston",
    "Russell",
    "Shirley",
    "Subiaco",
    "Success",
    "Summers",
    "Swifton",
    "Tinsman",
    "Trumann",
    "Turrell",
    "Tyronza",
    "Vilonia",
    "Walcott",
    "Waldron",
    "Widener",
    "Wilburn",
    "Winslow",
    "Woodson",
    "Wooster",
    "Alicia",
    "Almyra",
    "Alpena",
    "Alpine",
    "Amagon",
    "Atkins",
    "Aubrey",
    "Austin",
    "Avilla",
    "Beaver",
    "Beirne",
    "Benton",
    "Bodcaw",
    "Bowman",
    "Branch",
    "Bryant",
    "Calion",
    "Camden",
    "Conway",
    "Cotter",
    "DeWitt",
    "Dierks",
    "Drasco",
    "Elaine",
    "Elkins",
    "Etowah",
    "Eudora",
    "Fisher",
    "Floral",
    "Fulton",
    "Garner",
    "Gentry",
    "Gibson",
    "Goshen",
    "Grubbs",
    "Gurdon",
    "Halley",
    "Havana",
    "Haynes",
    "Hector",
    "Higden",
    "Hughes",
    "Hunter",
    "Huttig",
    "Jasper",
    "Jerome",
    "Joiner",
    "Keiser",
    "Kibler",
    "Knobel",
    "Lavaca",
    "Lawson",
    "Leslie",
    "Letona",
    "London",
    "Lonoke",
    "Louann",
    "Lowell",
    "Luxora",
    "Manila",
    "Marion",
    "McNeil",
    "Midway",
    "Monroe",
    "Morrow",
    "Newark",
    "Norman",
    "O'Kean",
    "Oneida",
    "Oppelo",
    "Oxford",
    "Parkin",
    "Patmos",
    "Pearcy",
    "Portia",
    "Reader",
    "Rector",
    "Rogers",
    "Roland",
    "Salado",
    "Sardis",
    "Searcy",
    "Sidney",
    "Stamps",
    "Staves",
    "Strong",
    "Summit",
    "Sunset",
    "Taylor",
    "Tillar",
    "Tucker",
    "Tupelo",
    "Urbana",
    "Warren",
    "Watson",
    "Wayton",
    "Weiner",
    "Weldon",
    "Wesley",
    "Wickes",
    "Wilmar",
    "Wilmot",
    "Wilson",
    "Wilton",
    "Acorn",
    "Adona",
    "Altus",
    "Amity",
    "Aplin",
    "Avoca",
    "Banks",
    "Beebe",
    "Boles",
    "Cabot",
    "Daisy",
    "Datto",
    "Desha",
    "Dover",
    "Dumas",
    "Dyess",
    "Earle",
    "Egypt",
    "Emmet",
    "Enola",
    "Fargo",
    "Floyd",
    "Fouke",
    "Genoa",
    "Gould",
    "Grady",
    "Guion",
    "Hardy",
    "Hazen",
    "Hoxie",
    "Kirby",
    "Lacey",
    "Lamar",
    "Leola",
    "Marie",
    "McNab",
    "McRae",
    "Ogden",
    "Omaha",
    "Ozark",
    "Ozone",
    "Paris",
    "Perla",
    "Perry",
    "Piney",
    "Ponca",
    "Poyen",
    "Pyatt",
    "Reyno",
    "Rison",
    "Rondo",
    "Rover",
    "Salem",
    "Scott",
    "Viola",
    "Waldo",
    "Wynne",
    "Alix",
    "Alma",
    "Bono",
    "Cale",
    "Casa",
    "Cash",
    "Colt",
    "Cove",
    "Deer",
    "Dell",
    "Diaz",
    "Dora",
    "Dyer",
    "Hope",
    "Ivan",
    "Lafe",
    "Lexa",
    "Lynn",
    "Mena",
    "Moro",
    "Oark",
    "Oden",
    "Ozan",
    "Reed",
    "Rudy",
    "Tull",
    "Ward",
    "Zinc",
    "Bay",
    "Coy",
    "Fox",
    "Guy",
    "Keo",
    "Ola",
    "Roe",
    "Rye",
    "Ulm",
]

AR_PLACES_UPPER = [p.upper() for p in AR_PLACES]
