# Generated by Django 6.0.8 on 2026-08-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Arkansas', 'Arkansas'), ('Ashley', 'Ashley'), ('Baxter', 'Baxter'), ('Benton', 'Benton'), ('Boone', 'Boone'), ('Bradley', 'Bradley'), ('Calhoun', 'Calhoun'), ('Carroll', 'Carroll'), ('Chicot', 'Chicot'), ('Clark', 'Clark'), ('Clay', 'Clay'), ('Cleburne', 'Cleburne'), ('Cleveland', 'Cleveland'), ('Columbia', 'Columbia'), ('Conway', 'Conway'), ('Craighead', 'Craighead'), ('Crawford', 'Crawford'), ('Crittenden', 'Crittenden'), ('Cross', 'Cross'), ('Dallas', 'Dallas'), ('Desha', 'Desha'), ('Drew', 'Drew'), ('Faulkner', 'Faulkner'), ('Franklin', 'Franklin'), ('Fulton', 'Fulton'), ('Garland', 'Garland'), ('Grant', 'Grant'), ('Greene', 'Greene'), ('Hempstead', 'Hempstead'), ('Hot Spring', 'Hot Spring'), ('Howard', 'Howard'), ('Independence', 'Independence'), ('Izard', 'Izard'), ('Jackson', 'Jackson'), ('Jefferson', 'Jefferson'), ('Johnson', 'Johnson'), ('Lafayette', 'Lafayette'), ('Lawrence', 'Lawrence'), ('Lee', 'Lee'), ('Lincoln', 'Lincoln'), ('Little River', 'Little River'), ('Logan', 'Logan'), ('Lonoke', 'Lonoke'), ('Madison', 'Madison'), ('Marion', 'Marion'), ('Miller', 'Miller'), ('Mississippi', 'Mississippi'), ('Monroe', 'Monroe'), ('Montgomery', 'Montgomery'), ('Nevada', 'Nevada'), ('Newton', 'Newton'), ('Ouachita', 'Ouachita'), ('Perry', 'Perry'), ('Phillips', 'Phillips'), ('Pike', 'Pike'), ('Poinsett', 'Poinsett'), ('Polk', 'Polk'), ('Pope', 'Pope'), ('Prairie', 'Prairie'), ('Pulaski', 'Pulaski'), ('Randolph', 'Randolph'), ('Saline', 'Saline'), ('Scott', 'Scott'), ('Searcy', 'Searcy'), ('Sebastian', 'Sebastian'), ('Sevier', 'Sevier'), ('Sharp', 'Sharp'), ('St. Francis', 'St. Francis'), ('Stone', 'Stone'), ('Union', 'Union'), ('UNKNOWN', 'UNKNOWN'), ('Van Buren', 'Van Buren'), ('Washington', 'Washington'), ('White', 'White'), ('Woodruff', 'Woodruff'), ('Yell', 'Yell')], max_length=64)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Complete'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('facilities_created', models.PositiveIntegerField(default=0)),
                ('inspections_created', models.PositiveIntegerField(default=0)),
                ('violations_created', models.PositiveIntegerField(default=0)),
                ('reports_downloaded', models.PositiveIntegerField(default=0)),
                ('progress_note', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=40, unique=True)),
                ('source_sequence_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='AR', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('raw_address', models.CharField(blank=True, max_length=400)),
                ('address_needs_review', models.BooleanField(default=False)),
                ('county', models.CharField(blank=True, choices=[('Arkansas', 'Arkansas'), ('Ashley', 'Ashley'), ('Baxter', 'Baxter'), ('Benton', 'Benton'), ('Boone', 'Boone'), ('Bradley', 'Bradley'), ('Calhoun', 'Calhoun'), ('Carroll', 'Carroll'), ('Chicot', 'Chicot'), ('Clark', 'Clark'), ('Clay', 'Clay'), ('Cleburne', 'Cleburne'), ('Cleveland', 'Cleveland'), ('Columbia', 'Columbia'), ('Conway', 'Conway'), ('Craighead', 'Craighead'), ('Crawford', 'Crawford'), ('Crittenden', 'Crittenden'), ('Cross', 'Cross'), ('Dallas', 'Dallas'), ('Desha', 'Desha'), ('Drew', 'Drew'), ('Faulkner', 'Faulkner'), ('Franklin', 'Franklin'), ('Fulton', 'Fulton'), ('Garland', 'Garland'), ('Grant', 'Grant'), ('Greene', 'Greene'), ('Hempstead', 'Hempstead'), ('Hot Spring', 'Hot Spring'), ('Howard', 'Howard'), ('Independence', 'Independence'), ('Izard', 'Izard'), ('Jackson', 'Jackson'), ('Jefferson', 'Jefferson'), ('Johnson', 'Johnson'), ('Lafayette', 'Lafayette'), ('Lawrence', 'Lawrence'), ('Lee', 'Lee'), ('Lincoln', 'Lincoln'), ('Little River', 'Little River'), ('Logan', 'Logan'), ('Lonoke', 'Lonoke'), ('Madison', 'Madison'), ('Marion', 'Marion'), ('Miller', 'Miller'), ('Mississippi', 'Mississippi'), ('Monroe', 'Monroe'), ('Montgomery', 'Montgomery'), ('Nevada', 'Nevada'), ('Newton', 'Newton'), ('Ouachita', 'Ouachita'), ('Perry', 'Perry'), ('Phillips', 'Phillips'), ('Pike', 'Pike'), ('Poinsett', 'Poinsett'), ('Polk', 'Polk'), ('Pope', 'Pope'), ('Prairie', 'Prairie'), ('Pulaski', 'Pulaski'), ('Randolph', 'Randolph'), ('Saline', 'Saline'), ('Scott', 'Scott'), ('Searcy', 'Searcy'), ('Sebastian', 'Sebastian'), ('Sevier', 'Sevier'), ('Sharp', 'Sharp'), ('St. Francis', 'St. Francis'), ('Stone', 'Stone'), ('Union', 'Union'), ('UNKNOWN', 'UNKNOWN'), ('Van Buren', 'Van Buren'), ('Washington', 'Washington'), ('White', 'White'), ('Woodruff', 'Woodruff'), ('Yell', 'Yell')], db_index=True, max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['county', 'name'], name='inspections_county_93ff32_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('inspection_type', models.CharField(blank=True, max_length=120)),
                ('sequence_within_day', models.PositiveSmallIntegerField(default=0)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('report_source_url', models.URLField(blank=True, max_length=500)),
                ('report_sha256', models.CharField(blank=True, max_length=64)),
                ('details_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.facility')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=120)),
                ('code_explanation', models.TextField(blank=True)),
                ('inspector_comments', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='inspections.inspection')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['-date', 'facility'], name='inspections_date_9d7529_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.UniqueConstraint(fields=('facility', 'date', 'inspection_type', 'sequence_within_day'), name='unique_inspection_natural_key'),
        ),
        migrations.AlterUniqueTogether(
            name='violation',
            unique_together={('inspection', 'ordinal')},
        ),
    ]
