# Generated by Django 6.0.8 on 2026-08-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_add_facility_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='geocode_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='geocode_last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
