# Generated by Django 6.0.8 on 2026-08-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_geocode_attempt_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='geocode_source',
            field=models.CharField(blank=True, choices=[('arkansas_gis', 'Arkansas GIS composite locator'), ('census', 'Census geocoder'), ('manual', 'Entered by hand'), ('adh_map', 'ADH map payload (retired)')], db_index=True, max_length=16),
        ),
    ]
