# Generated by Django 6.0.8 on 2026-08-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_arkansas_gis_geocoder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='report_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='source_inspection_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inspection',
            name='violations_source',
            field=models.CharField(blank=True, choices=[('pdf', 'Inspection report PDF'), ('web', 'Website observations overlay')], max_length=4),
        ),
        migrations.AddField(
            model_name='violation',
            name='correct_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='item_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='violation',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('P', 'Priority'), ('PF', 'Priority Foundation'), ('C', 'Core')], db_index=True, max_length=2),
        ),
        migrations.AddField(
            model_name='violation',
            name='source',
            field=models.CharField(choices=[('pdf', 'Inspection report PDF'), ('web', 'Website observations overlay')], db_index=True, default='web', max_length=4),
        ),
    ]
