# Generated by Django 6.0.8 on 2026-08-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_violations_from_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='violations_from_pdf',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
