# Generated by Django 6.0.8 on 2026-08-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_run_pdf_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationItem',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('RISK_FACTORS', 'Foodborne illness risk factors'), ('GOOD_RETAIL_PRACTICES', 'Good retail practices')], db_index=True, max_length=24)),
                ('subsection', models.CharField(blank=True, max_length=120)),
                ('official_description', models.TextField()),
                ('plain_description', models.TextField(blank=True, help_text='Reader-facing wording. Overrides the official text on the site.')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='violation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='inspections.violationitem'),
        ),
    ]
