# Generated by Django 6.0.8 on 2026-08-21 09:56

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_seed_violation_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Arkansas', 'Arkansas'), ('Ashley', 'Ashley'), ('Baxter', 'Baxter'), ('Benton', 'Benton'), ('Boone', 'Boone'), ('Bradley', 'Bradley'), ('Calhoun', 'Calhoun'), ('Carroll', 'Carroll'), ('Chicot', 'Chicot'), ('Clark', 'Clark'), ('Clay', 'Clay'), ('Cleburne', 'Cleburne'), ('Cleveland', 'Cleveland'), ('Columbia', 'Columbia'), ('Conway', 'Conway'), ('Craighead', 'Craighead'), ('Crawford', 'Crawford'), ('Crittenden', 'Crittenden'), ('Cross', 'Cross'), ('Dallas', 'Dallas'), ('Desha', 'Desha'), ('Drew', 'Drew'), ('Faulkner', 'Faulkner'), ('Franklin', 'Franklin'), ('Fulton', 'Fulton'), ('Garland', 'Garland'), ('Grant', 'Grant'), ('Greene', 'Greene'), ('Hempstead', 'Hempstead'), ('Hot Spring', 'Hot Spring'), ('Howard', 'Howard'), ('Independence', 'Independence'), ('Izard', 'Izard'), ('Jackson', 'Jackson'), ('Jefferson', 'Jefferson'), ('Johnson', 'Johnson'), ('Lafayette', 'Lafayette'), ('Lawrence', 'Lawrence'), ('Lee', 'Lee'), ('Lincoln', 'Lincoln'), ('Little River', 'Little River'), ('Logan', 'Logan'), ('Lonoke', 'Lonoke'), ('Madison', 'Madison'), ('Marion', 'Marion'), ('Miller', 'Miller'), ('Mississippi', 'Mississippi'), ('Monroe', 'Monroe'), ('Montgomery', 'Montgomery'), ('Nevada', 'Nevada'), ('Newton', 'Newton'), ('Ouachita', 'Ouachita'), ('Perry', 'Perry'), ('Phillips', 'Phillips'), ('Pike', 'Pike'), ('Poinsett', 'Poinsett'), ('Polk', 'Polk'), ('Pope', 'Pope'), ('Prairie', 'Prairie'), ('Pulaski', 'Pulaski'), ('Randolph', 'Randolph'), ('Saline', 'Saline'), ('Scott', 'Scott'), ('Searcy', 'Searcy'), ('Sebastian', 'Sebastian'), ('Sevier', 'Sevier'), ('Sharp', 'Sharp'), ('St. Francis', 'St. Francis'), ('Stone', 'Stone'), ('Union', 'Union'), ('UNKNOWN', 'UNKNOWN'), ('Van Buren', 'Van Buren'), ('Washington', 'Washington'), ('White', 'White'), ('Woodruff', 'Woodruff'), ('Yell', 'Yell')], max_length=64, unique=True)),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Every week'), ('biweekly', 'Every two weeks'), ('monthly', 'Every month')], default='weekly', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For weekly and biweekly schedules.', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='For monthly schedules. Capped at 28 so every month has the date.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('run_at', models.TimeField(default=datetime.time(2, 0), help_text="Local time of day to start. Overnight is kindest to the state's server.")),
                ('lookback_days', models.PositiveSmallIntegerField(default=30, help_text='How far back each run searches. Must overlap the interval — inspections often appear online well after the date they happened.')),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_queued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspections.scraperun')),
            ],
            options={
                'ordering': ['county'],
            },
        ),
        migrations.AddField(
            model_name='scraperun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='inspections.scrapeschedule'),
        ),
    ]
