# Generated by Django 6.0.8 on 2026-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_scrape_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Appears in the embed URL.', max_length=80, unique=True)),
                ('publication', models.CharField(blank=True, help_text='Which paper this is for. Internal only.', max_length=120)),
                ('county', models.CharField(choices=[('Arkansas', 'Arkansas'), ('Ashley', 'Ashley'), ('Baxter', 'Baxter'), ('Benton', 'Benton'), ('Boone', 'Boone'), ('Bradley', 'Bradley'), ('Calhoun', 'Calhoun'), ('Carroll', 'Carroll'), ('Chicot', 'Chicot'), ('Clark', 'Clark'), ('Clay', 'Clay'), ('Cleburne', 'Cleburne'), ('Cleveland', 'Cleveland'), ('Columbia', 'Columbia'), ('Conway', 'Conway'), ('Craighead', 'Craighead'), ('Crawford', 'Crawford'), ('Crittenden', 'Crittenden'), ('Cross', 'Cross'), ('Dallas', 'Dallas'), ('Desha', 'Desha'), ('Drew', 'Drew'), ('Faulkner', 'Faulkner'), ('Franklin', 'Franklin'), ('Fulton', 'Fulton'), ('Garland', 'Garland'), ('Grant', 'Grant'), ('Greene', 'Greene'), ('Hempstead', 'Hempstead'), ('Hot Spring', 'Hot Spring'), ('Howard', 'Howard'), ('Independence', 'Independence'), ('Izard', 'Izard'), ('Jackson', 'Jackson'), ('Jefferson', 'Jefferson'), ('Johnson', 'Johnson'), ('Lafayette', 'Lafayette'), ('Lawrence', 'Lawrence'), ('Lee', 'Lee'), ('Lincoln', 'Lincoln'), ('Little River', 'Little River'), ('Logan', 'Logan'), ('Lonoke', 'Lonoke'), ('Madison', 'Madison'), ('Marion', 'Marion'), ('Miller', 'Miller'), ('Mississippi', 'Mississippi'), ('Monroe', 'Monroe'), ('Montgomery', 'Montgomery'), ('Nevada', 'Nevada'), ('Newton', 'Newton'), ('Ouachita', 'Ouachita'), ('Perry', 'Perry'), ('Phillips', 'Phillips'), ('Pike', 'Pike'), ('Poinsett', 'Poinsett'), ('Polk', 'Polk'), ('Pope', 'Pope'), ('Prairie', 'Prairie'), ('Pulaski', 'Pulaski'), ('Randolph', 'Randolph'), ('Saline', 'Saline'), ('Scott', 'Scott'), ('Searcy', 'Searcy'), ('Sebastian', 'Sebastian'), ('Sevier', 'Sevier'), ('Sharp', 'Sharp'), ('St. Francis', 'St. Francis'), ('Stone', 'Stone'), ('Union', 'Union'), ('UNKNOWN', 'UNKNOWN'), ('Van Buren', 'Van Buren'), ('Washington', 'Washington'), ('White', 'White'), ('Woodruff', 'Woodruff'), ('Yell', 'Yell')], max_length=64)),
                ('window_days', models.PositiveSmallIntegerField(blank=True, default=30, help_text="Rolling window, e.g. 30 for 'the last 30 days'. Leave blank to use fixed dates.", null=True)),
                ('date_from', models.DateField(blank=True, help_text='Fixed range, for a specific story.', null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('title_override', models.CharField(blank=True, help_text="Replaces the automatic '<County> County Health Inspections' heading.", max_length=200)),
                ('rows_per_page', models.PositiveSmallIntegerField(default=20, help_text='0 shows every row without paging.')),
                ('row_limit', models.PositiveSmallIntegerField(default=500, help_text="Hard cap on rows sent to the browser. Paging and sorting happen in the reader's browser, which stops being viable past ~1000.")),
                ('default_sort', models.CharField(choices=[('date_desc', 'Date, newest first'), ('date_asc', 'Date, oldest first'), ('name_asc', 'Facility name, A–Z'), ('violations_desc', 'Most violations first')], default='date_desc', max_length=20)),
                ('search_enabled', models.BooleanField(default=True, help_text='Searches facility name and address/city.')),
                ('show_report_links', models.BooleanField(default=True, help_text='Link each inspection to its source PDF.')),
                ('is_active', models.BooleanField(default=True, help_text='Switching this off blanks the embed everywhere it appears, without anyone editing their CMS.')),
                ('notes', models.TextField(blank=True, help_text='Internal only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['county', 'slug'],
            },
        ),
    ]
