# Generated by Django 6.0.8 on 2026-09-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_embed_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What you'll pick between later, e.g. 'Terser, September 2026'.", max_length=120, unique=True)),
                ('system_prompt', models.TextField(help_text='The instructions. Rules 1 and 2 are load-bearing: they are what keeps the model quoting the inspector instead of explaining what a violation usually means. Change them only deliberately.')),
                ('user_template', models.TextField(blank=True, help_text='Optional wrapper for the export, e.g. an example of a good summary to work from. Use {html} where the inspections should go. Leave blank to send the export on its own, which is the default.')),
                ('model', models.CharField(blank=True, help_text='Overrides OPENAI_MODEL for this prompt only. Leave blank to use whatever the environment is set to.', max_length=80)),
                ('is_active', models.BooleanField(default=False, help_text='Exactly one prompt is active. Ticking this unticks the others.')),
                ('notes', models.TextField(blank=True, help_text='Internal only. What you changed and why.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_summary_prompt')],
            },
        ),
    ]
