# Generated by Django 6.0.8 on 2026-09-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_markdown_summary_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='geocode_source',
            field=models.CharField(blank=True, choices=[('arkansas_gis', 'Arkansas GIS composite locator'), ('arkansas_ng911', 'Arkansas GIS NG911 address lookup'), ('census', 'Census geocoder'), ('manual', 'Entered by hand'), ('adh_map', 'ADH map payload (retired)')], db_index=True, max_length=16),
        ),
    ]
