# Generated by Django 6.0.8 on 2026-09-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_alter_facility_geocode_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='inspection_count',
            field=models.PositiveIntegerField(default=0, help_text='Total inspections on record — the whole history, unlike the counts above.'),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_core',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_inspection',
            field=models.ForeignKey(blank=True, help_text='The most recent inspection. Derived; do not edit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_inspection_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_inspection_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_priority_foundation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='latest_violation_total',
            field=models.PositiveSmallIntegerField(default=0, help_text='Violations at the most recent inspection only.'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['county', '-latest_inspection_date'], name='inspections_county_7fbae4_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['county', '-latest_violation_total'], name='inspections_county_10b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['-latest_inspection_date'], name='inspections_latest__137a65_idx'),
        ),
    ]
