# Generated by Django 6.0.8 on 2026-09-13 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_backfill_latest_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Appears in the URL.', max_length=80, unique=True)),
                ('publication', models.CharField(blank=True, help_text='Which paper this is for. Internal only.', max_length=120)),
                ('counties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Arkansas', 'Arkansas'), ('Ashley', 'Ashley'), ('Baxter', 'Baxter'), ('Benton', 'Benton'), ('Boone', 'Boone'), ('Bradley', 'Bradley'), ('Calhoun', 'Calhoun'), ('Carroll', 'Carroll'), ('Chicot', 'Chicot'), ('Clark', 'Clark'), ('Clay', 'Clay'), ('Cleburne', 'Cleburne'), ('Cleveland', 'Cleveland'), ('Columbia', 'Columbia'), ('Conway', 'Conway'), ('Craighead', 'Craighead'), ('Crawford', 'Crawford'), ('Crittenden', 'Crittenden'), ('Cross', 'Cross'), ('Dallas', 'Dallas'), ('Desha', 'Desha'), ('Drew', 'Drew'), ('Faulkner', 'Faulkner'), ('Franklin', 'Franklin'), ('Fulton', 'Fulton'), ('Garland', 'Garland'), ('Grant', 'Grant'), ('Greene', 'Greene'), ('Hempstead', 'Hempstead'), ('Hot Spring', 'Hot Spring'), ('Howard', 'Howard'), ('Independence', 'Independence'), ('Izard', 'Izard'), ('Jackson', 'Jackson'), ('Jefferson', 'Jefferson'), ('Johnson', 'Johnson'), ('Lafayette', 'Lafayette'), ('Lawrence', 'Lawrence'), ('Lee', 'Lee'), ('Lincoln', 'Lincoln'), ('Little River', 'Little River'), ('Logan', 'Logan'), ('Lonoke', 'Lonoke'), ('Madison', 'Madison'), ('Marion', 'Marion'), ('Miller', 'Miller'), ('Mississippi', 'Mississippi'), ('Monroe', 'Monroe'), ('Montgomery', 'Montgomery'), ('Nevada', 'Nevada'), ('Newton', 'Newton'), ('Ouachita', 'Ouachita'), ('Perry', 'Perry'), ('Phillips', 'Phillips'), ('Pike', 'Pike'), ('Poinsett', 'Poinsett'), ('Polk', 'Polk'), ('Pope', 'Pope'), ('Prairie', 'Prairie'), ('Pulaski', 'Pulaski'), ('Randolph', 'Randolph'), ('Saline', 'Saline'), ('Scott', 'Scott'), ('Searcy', 'Searcy'), ('Sebastian', 'Sebastian'), ('Sevier', 'Sevier'), ('Sharp', 'Sharp'), ('St. Francis', 'St. Francis'), ('Stone', 'Stone'), ('Union', 'Union'), ('UNKNOWN', 'UNKNOWN'), ('Van Buren', 'Van Buren'), ('Washington', 'Washington'), ('White', 'White'), ('Woodruff', 'Woodruff'), ('Yell', 'Yell')], max_length=64), help_text="Every county in this paper's readership area.")),
                ('title_override', models.CharField(blank=True, help_text="Replaces the automatic 'Health inspections' heading.", max_length=200)),
                ('rows_per_page', models.PositiveSmallIntegerField(default=25, help_text='Rows per page in the table. The map always shows every match, whatever page the reader is on.')),
                ('is_active', models.BooleanField(default=True, help_text='Switching this off blanks the dashboard everywhere it appears, without anyone editing their CMS.')),
                ('notes', models.TextField(blank=True, help_text='Internal only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
